FROM openjdk:11-jdk

VOLUME /tmp

ARG JAR_FILE=./build/libs/gjgs-1.0.jar

COPY ${JAR_FILE} app.jar

# file: 는 있어도 없어도 된다.
ENTRYPOINT ["nohup","java","-jar","app.jar","2>&1","&"]


#ENTRYPOINT ["java","-jar","app.jar","--spring.config.location=/config/application.yml"]

