-- MySQL Script generated by MySQL Workbench
-- Fri Oct 22 16:39:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gjgs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gjgs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gjgs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `gjgs` ;

-- -----------------------------------------------------
-- Table `gjgs`.`zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`zone` (
    `zone_id` BIGINT NOT NULL AUTO_INCREMENT,
    `main_zone` VARCHAR(255) NOT NULL,
    `sub_zone` VARCHAR(255) NULL,
    PRIMARY KEY (`zone_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gjgs`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`member` (
    `member_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `age` INT NOT NULL,
    `authority` VARCHAR(30) NOT NULL DEFAULT 'ROLE_USER',
    `director_text` VARCHAR(255) NULL DEFAULT NULL,
    `fcm_token` VARCHAR(255) NULL DEFAULT NULL,
    `image_file_name` LONGTEXT NULL DEFAULT NULL,
    `image_file_url` LONGTEXT NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `nickname` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(255) NOT NULL,
    `profile_text` VARCHAR(255) NULL DEFAULT NULL,
    `sex` VARCHAR(255) NOT NULL,
    `total_reward` INT NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `zone_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`member_id`),
    CONSTRAINT `FK_MEMBER_ZONE`
    FOREIGN KEY (`zone_id`)
    REFERENCES `gjgs`.`zone` (`zone_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK_MEMBER_NICKNAME` ON `gjgs`.`member` (`nickname` ASC) VISIBLE;

CREATE UNIQUE INDEX `UK_MEMBER_PHONE` ON `gjgs`.`member` (`phone` ASC) VISIBLE;

CREATE UNIQUE INDEX `UK_MEMBER_USERNAME` ON `gjgs`.`member` (`username` ASC) VISIBLE;

CREATE INDEX `FK_MEMBER_ZONE` ON `gjgs`.`member` (`zone_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`team` (
    `team_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `current_member_count` INT NOT NULL DEFAULT '1',
    `day_type` VARCHAR(255) NOT NULL,
    `max_people` INT NOT NULL,
    `team_name` VARCHAR(255) NOT NULL,
    `time_type` VARCHAR(255) NOT NULL,
    `member_id` BIGINT NOT NULL,
    `zone_id` BIGINT NOT NULL,
    PRIMARY KEY (`team_id`),
    CONSTRAINT `FK_TEAM_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_TEAM_ZONE`
    FOREIGN KEY (`zone_id`)
    REFERENCES `gjgs`.`zone` (`zone_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_TEAM_MEMBER` ON `gjgs`.`team` (`member_id` ASC) VISIBLE;

CREATE INDEX `FK_TEAM_ZONE` ON `gjgs`.`team` (`zone_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`category` (
    `category_id` BIGINT NOT NULL AUTO_INCREMENT,
    `main_category` VARCHAR(255) NOT NULL,
    `sub_category` VARCHAR(255) NULL,
    PRIMARY KEY (`category_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gjgs`.`lecture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`lecture` (
    `lecture_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `click_count` INT NULL DEFAULT '0',
    `favorite_count` INT NULL DEFAULT '0',
    `finished` BIT(1) NOT NULL,
    `full_address` VARCHAR(255) NOT NULL,
    `lecture_status` VARCHAR(255) NOT NULL,
    `main_text` VARCHAR(255) NULL,
    `max_participants` INT NULL,
    `min_participants` INT NULL,
    `only_gjgs` TINYINT(1) NULL DEFAULT '0',
    `price_four` INT NOT NULL,
    `price_one` INT NOT NULL,
    `price_three` INT NOT NULL,
    `price_two` INT NOT NULL,
    `regular_price` INT NOT NULL,
    `progress_time` INT NULL,
    `reject_reason` VARCHAR(255) NULL DEFAULT NULL,
    `score` DOUBLE NULL,
    `terms_four` BIT(1) NOT NULL,
    `terms_one` BIT(1) NOT NULL,
    `terms_three` BIT(1) NOT NULL,
    `terms_two` BIT(1) NOT NULL,
    `thumbnail_image_file_name` LONGTEXT NOT NULL,
    `thumbnail_image_file_url` LONGTEXT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `category_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    `zone_id` BIGINT NOT NULL,
    PRIMARY KEY (`lecture_id`),
    CONSTRAINT `FK_LECTURE_ZONE`
    FOREIGN KEY (`zone_id`)
    REFERENCES `gjgs`.`zone` (`zone_id`),
    CONSTRAINT `FK_LECTURE_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_LECTURE_CATEGORY`
    FOREIGN KEY (`category_id`)
    REFERENCES `gjgs`.`category` (`category_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_LECTURE_CATEGORY` ON `gjgs`.`lecture` (`category_id` ASC) VISIBLE;

CREATE INDEX `FK_LECTURE_MEMBER` ON `gjgs`.`lecture` (`member_id` ASC) VISIBLE;

CREATE INDEX `FK_LECTURE_ZONE` ON `gjgs`.`lecture` (`zone_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`bulletin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`bulletin` (
    `bulletin_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `age` VARCHAR(255) NOT NULL,
    `day_type` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `status` TINYINT(1) NOT NULL DEFAULT '1',
    `time_type` VARCHAR(255) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `lecture_id` BIGINT NOT NULL,
    `team_id` BIGINT NOT NULL,
    PRIMARY KEY (`bulletin_id`),
    CONSTRAINT `FK_BULLETIN_TEAM`
    FOREIGN KEY (`team_id`)
    REFERENCES `gjgs`.`team` (`team_id`),
    CONSTRAINT `FK_BULLETIN_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `FK_BULLETIN_TEAM` ON `gjgs`.`bulletin` (`team_id` ASC) VISIBLE;

CREATE INDEX `FK_BULLETIN_LECTURE` ON `gjgs`.`bulletin` (`lecture_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`bulletin_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`bulletin_category` (
    `bulletin_category_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `bulletin_id` BIGINT NOT NULL,
    `category_id` BIGINT NOT NULL,
    PRIMARY KEY (`bulletin_category_id`),
    CONSTRAINT `FK_BULLETIN_CATEGORY_CATEGORY`
    FOREIGN KEY (`category_id`)
    REFERENCES `gjgs`.`category` (`category_id`),
    CONSTRAINT `FK_BULLETUN_CATEGORY_BULLETIN`
    FOREIGN KEY (`bulletin_id`)
    REFERENCES `gjgs`.`bulletin` (`bulletin_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_BULLETUN_CATEGORY_BULLETIN` ON `gjgs`.`bulletin_category` (`bulletin_id` ASC) VISIBLE;

CREATE INDEX `FK_BULLETIN_CATEGORY_CATEGORY` ON `gjgs`.`bulletin_category` (`category_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`bulletin_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`bulletin_member` (
    `bulletin_member_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `bulletin_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`bulletin_member_id`),
    CONSTRAINT `FK_BULLETIN_MEMBER_BULLETIN`
    FOREIGN KEY (`bulletin_id`)
    REFERENCES `gjgs`.`bulletin` (`bulletin_id`),
    CONSTRAINT `FK_BULLETIN_MEMBER_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_BULLETIN_MEMBER_BULLETIN` ON `gjgs`.`bulletin_member` (`bulletin_id` ASC) VISIBLE;

CREATE INDEX `FK_BULLETIN_MEMBER_MEMBER` ON `gjgs`.`bulletin_member` (`member_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`bulletin_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`bulletin_zone` (
    `bulletin_zone_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `bulletin_id` BIGINT NOT NULL,
    `zone_id` BIGINT NOT NULL,
    PRIMARY KEY (`bulletin_zone_id`),
    CONSTRAINT `FK_BULLETIN_ZONE_ZONE`
    FOREIGN KEY (`zone_id`)
    REFERENCES `gjgs`.`zone` (`zone_id`),
    CONSTRAINT `FK_BULLETIN_ZONE_BULLETIN`
    FOREIGN KEY (`bulletin_id`)
    REFERENCES `gjgs`.`bulletin` (`bulletin_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_BULLETIN_ZONE_BULLETIN` ON `gjgs`.`bulletin_zone` (`bulletin_id` ASC) VISIBLE;

CREATE INDEX `FK_BULLETIN_ZONE_ZONE` ON `gjgs`.`bulletin_zone` (`zone_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`coupon` (
    `coupon_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `available` BIT(1) NOT NULL,
    `charge_count` INT NOT NULL,
    `close_date` DATETIME(6) NULL,
    `discount_price` INT NOT NULL,
    `issue_date` DATETIME(6) NULL,
    `receive_people` INT NOT NULL,
    `remain_count` INT NOT NULL,
    `serial_number` VARCHAR(255) NULL DEFAULT NULL,
    `title` VARCHAR(255) NOT NULL,
    `lecture_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`coupon_id`),
    CONSTRAINT `FK_COUPON_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK_COUPON_SERIAL_NUMBER` ON `gjgs`.`coupon` (`serial_number` ASC) VISIBLE;

CREATE INDEX `FK_COUPON_LECTURE` ON `gjgs`.`coupon` (`lecture_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`curriculum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`curriculum` (
    `curriculum_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `curriculum_image_name` VARCHAR(255) NOT NULL,
    `curriculum_image_url` VARCHAR(255) NOT NULL,
    `detail_text` VARCHAR(255) NOT NULL,
    `orders` INT NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `lecture_id` BIGINT NOT NULL,
    PRIMARY KEY (`curriculum_id`),
    CONSTRAINT `FK_CURRICULUM_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_CURRICULUM_LECTURE` ON `gjgs`.`curriculum` (`lecture_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`finished_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`finished_product` (
                                                         `finished_product_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                         `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `finished_product_image_name` VARCHAR(255) NOT NULL,
    `finished_product_image_url` VARCHAR(255) NOT NULL,
    `orders` INT NOT NULL,
    `text` VARCHAR(255) NOT NULL,
    `lecture_id` BIGINT NOT NULL,
    PRIMARY KEY (`finished_product_id`),
    CONSTRAINT `FK_FINISHED_PRODUCT_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_FINISHED_PRODUCT_LECTURE` ON `gjgs`.`finished_product` (`lecture_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`lecture_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`lecture_member` (
    `lecture_member_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `lecture_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`lecture_member_id`),
    CONSTRAINT `FK_LECTURE_MEMBER_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_LECTURE_MEMBER_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_LECTURE_MEMBER_LECTURE` ON `gjgs`.`lecture_member` (`lecture_id` ASC) VISIBLE;

CREATE INDEX `FK_LECTURE_MEMBER_MEMBER` ON `gjgs`.`lecture_member` (`member_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`lecture_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`lecture_team` (
    `lecture_team_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `lecture_id` BIGINT NOT NULL,
    `team_id` BIGINT NOT NULL,
    PRIMARY KEY (`lecture_team_id`),
    CONSTRAINT `FK_LECTURE_TEAM_TEAM`
    FOREIGN KEY (`team_id`)
    REFERENCES `gjgs`.`team` (`team_id`),
    CONSTRAINT `FK_LECTURE_TEAM_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_LECTURE_TEAM_LECTURE` ON `gjgs`.`lecture_team` (`lecture_id` ASC) VISIBLE;

CREATE INDEX `FK_LECTURE_TEAM_TEAM` ON `gjgs`.`lecture_team` (`team_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`matching`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`matching` (
    `matching_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `day_type` VARCHAR(255) NOT NULL,
    `prefer_member_count` INT NOT NULL,
    `time_type` VARCHAR(255) NOT NULL,
    `category_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    `zone_id` BIGINT NOT NULL,
    PRIMARY KEY (`matching_id`),
    CONSTRAINT `FK_MATCHING_ZONE`
    FOREIGN KEY (`zone_id`)
    REFERENCES `gjgs`.`zone` (`zone_id`),
    CONSTRAINT `FK_MATCHING_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_MATCHING_CATEGORY`
    FOREIGN KEY (`category_id`)
    REFERENCES `gjgs`.`category` (`category_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_MATCHING_CATEGORY` ON `gjgs`.`matching` (`category_id` ASC) VISIBLE;

CREATE INDEX `FK_MATCHING_MEMBER` ON `gjgs`.`matching` (`member_id` ASC) VISIBLE;

CREATE INDEX `FK_MATCHING_ZONE` ON `gjgs`.`matching` (`zone_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`member_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`member_category` (
    `member_catagory_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `category_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`member_catagory_id`),
    CONSTRAINT `FK_MEMBER_CATEGORY_CATEGORY`
    FOREIGN KEY (`category_id`)
    REFERENCES `gjgs`.`category` (`category_id`),
    CONSTRAINT `FK_MEMBER_CATEGORY_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_MEMBER_CATEGORY_CATEGORY` ON `gjgs`.`member_category` (`category_id` ASC) VISIBLE;

CREATE INDEX `FK_MEMBER_CATEGORY_MEMBER` ON `gjgs`.`member_category` (`member_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`member_coupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`member_coupon` (
    `member_coupon_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `discount_price` INT NOT NULL,
    `serial_number` VARCHAR(255) NULL DEFAULT NULL,
    `used` BIT(1) NOT NULL,
    `coupon_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`member_coupon_id`),
    CONSTRAINT `FK_MEMBER_COUPON_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_MEMBER_COUPON_COUPON`
    FOREIGN KEY (`coupon_id`)
    REFERENCES `gjgs`.`coupon` (`coupon_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK_MEMBER_COUPON_SERIAL_NUMBER` ON `gjgs`.`member_coupon` (`serial_number` ASC) VISIBLE;

CREATE INDEX `FK_MEMBER_COUPON_COUPON` ON `gjgs`.`member_coupon` (`coupon_id` ASC) VISIBLE;

CREATE INDEX `FK_MEMBER_COUPON_MEMBER` ON `gjgs`.`member_coupon` (`member_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`member_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`member_team` (
    `member_team_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `member_id` BIGINT NOT NULL,
    `team_id` BIGINT NOT NULL,
    PRIMARY KEY (`member_team_id`),
    CONSTRAINT `FK_MEMBER_TEAM_TEAM`
    FOREIGN KEY (`team_id`)
    REFERENCES `gjgs`.`team` (`team_id`),
    CONSTRAINT `FK_MEMBER_TEAM_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `UK_MEMBER_TEAM_MEMBER_ID_TEAM_ID` ON `gjgs`.`member_team` (`member_id` ASC, `team_id` ASC) VISIBLE;

CREATE INDEX `FK_MEMBER_TEAM_TEAM` ON `gjgs`.`member_team` (`team_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`notice` (
    `notice_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `notice_type` VARCHAR(255) NOT NULL,
    `text` VARCHAR(255) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`notice_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `gjgs`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`notification` (
    `notification_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `team_id` BIGINT NULL DEFAULT NULL,
    `checked` BIT(1) NOT NULL,
    `message` VARCHAR(255) NOT NULL,
    `notification_type` VARCHAR(255) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`notification_id`),
    CONSTRAINT `FK_NOTIFICATION_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_NOTIFICATION_MEMBER` ON `gjgs`.`notification` (`member_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`reward` (
    `reward_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `amount` INT NOT NULL,
    `reward_type` VARCHAR(255) NOT NULL,
    `text` VARCHAR(255) NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`reward_id`),
    CONSTRAINT `FK_REWARD_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_REWARD_MEMBER` ON `gjgs`.`reward` (`member_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`schedule` (
    `schedule_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `current_participants` INT NOT NULL,
    `end_time` TIME NOT NULL,
    `lecture_date` DATE NOT NULL,
    `progress_minutes` INT NOT NULL,
    `schedule_status` VARCHAR(255) NOT NULL,
    `start_time` TIME NOT NULL,
    `lecture_id` BIGINT NOT NULL,
    PRIMARY KEY (`schedule_id`),
    CONSTRAINT `FK_SCHEDULE_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_SCHEDULE_LECTURE` ON `gjgs`.`schedule` (`lecture_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`orders` (
    `order_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `discount_price` INT NOT NULL,
    `final_price` INT NOT NULL,
    `iamport_uid` VARCHAR(255) NULL DEFAULT NULL,
    `order_status` VARCHAR(255) NOT NULL,
    `original_price` INT NOT NULL,
    `uuid` VARCHAR(255) NOT NULL,
    `member_id` BIGINT NOT NULL,
    `member_coupon_id` BIGINT NULL DEFAULT NULL,
    `reward_id` BIGINT NULL DEFAULT NULL,
    `schedule_id` BIGINT NOT NULL,
    `team_id` BIGINT NULL DEFAULT NULL,
    PRIMARY KEY (`order_id`),
    CONSTRAINT `FK_ORDERS_REWARD`
    FOREIGN KEY (`reward_id`)
    REFERENCES `gjgs`.`reward` (`reward_id`),
    CONSTRAINT `FK_ORDERS_MEMBER_COUPON`
    FOREIGN KEY (`member_coupon_id`)
    REFERENCES `gjgs`.`member_coupon` (`member_coupon_id`),
    CONSTRAINT `FK_ORDERS_TEAM`
    FOREIGN KEY (`team_id`)
    REFERENCES `gjgs`.`team` (`team_id`),
    CONSTRAINT `FK_ORDERS_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_ORDERS_SCHEDULE`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `gjgs`.`schedule` (`schedule_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_ORDERS_MEMBER` ON `gjgs`.`orders` (`member_id` ASC) VISIBLE;

CREATE INDEX `FK_ORDERS_MEMBER_COUPON` ON `gjgs`.`orders` (`member_coupon_id` ASC) VISIBLE;

CREATE INDEX `FK_ORDERS_REWARD` ON `gjgs`.`orders` (`reward_id` ASC) VISIBLE;

CREATE INDEX `FK_ORDERS_SCHEDULE` ON `gjgs`.`orders` (`schedule_id` ASC) VISIBLE;

CREATE INDEX `FK_ORDERS_TEAM` ON `gjgs`.`orders` (`team_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`participant` (
    `participant_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `member_id` BIGINT NOT NULL,
    `schedule_id` BIGINT NOT NULL,
    PRIMARY KEY (`participant_id`),
    CONSTRAINT `FK_PARTICIPANT_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_PARTICIPANT_SCHEDULE`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `gjgs`.`schedule` (`schedule_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_PARTICIPANT_MEMBER` ON `gjgs`.`participant` (`member_id` ASC) VISIBLE;

CREATE INDEX `FK_PARTICIPANT_SCHEDULE` ON `gjgs`.`participant` (`schedule_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`question` (
    `question_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `main_text` VARCHAR(255) NOT NULL,
    `question_status` VARCHAR(255) NOT NULL,
    `reply_text` VARCHAR(255) NULL DEFAULT NULL,
    `lecture_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`question_id`),
    CONSTRAINT `FK_QUESTION_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_QUESTION_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_QUESTION_LECTURE` ON `gjgs`.`question` (`lecture_id` ASC) VISIBLE;

CREATE INDEX `FK_QUESTION_MEMBER` ON `gjgs`.`question` (`member_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`review` (
    `review_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `reply_text` VARCHAR(255) NULL DEFAULT NULL,
    `review_image_file_url` VARCHAR(255) NULL DEFAULT NULL,
    `score` INT NOT NULL,
    `text` VARCHAR(255) NOT NULL,
    `lecture_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`review_id`),
    CONSTRAINT `FK_REVIEW_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`),
    CONSTRAINT `FK_REVIEW_LECTURE`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `gjgs`.`lecture` (`lecture_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_REVIEW_LECTURE` ON `gjgs`.`review` (`lecture_id` ASC) VISIBLE;

CREATE INDEX `FK_REVIEW_MEMBER` ON `gjgs`.`review` (`member_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`team_applier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`team_applier` (
    `team_applier_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `team_id` BIGINT NOT NULL,
    `member_id` BIGINT NOT NULL,
    PRIMARY KEY (`team_applier_id`),
    CONSTRAINT `FK_TEAM_APPLIER_TEAM`
    FOREIGN KEY (`team_id`)
    REFERENCES `gjgs`.`team` (`team_id`),
    CONSTRAINT `FK_TEAM_APPLIER_MEMBER`
    FOREIGN KEY (`member_id`)
    REFERENCES `gjgs`.`member` (`member_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `FK_TEAM_APPLIER_MEMBER` ON `gjgs`.`team_applier` (`member_id` ASC, `team_id` ASC) VISIBLE;

CREATE INDEX `FK_TEAM_APPLIER_TEAM` ON `gjgs`.`team_applier` (`team_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `gjgs`.`team_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gjgs`.`team_category` (
    `team_catagory_id` BIGINT NOT NULL AUTO_INCREMENT,
    `created_date` DATETIME(6) NULL DEFAULT NULL,
    `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
    `category_id` BIGINT NOT NULL,
    `team_id` BIGINT NOT NULL,
    PRIMARY KEY (`team_catagory_id`),
    CONSTRAINT `FK_TEAM_CATEGORY_CATEGORY`
    FOREIGN KEY (`category_id`)
    REFERENCES `gjgs`.`category` (`category_id`),
    CONSTRAINT `FK_TEAM_CATEGORY_TEAM`
    FOREIGN KEY (`team_id`)
    REFERENCES `gjgs`.`team` (`team_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_TEAM_CATEGORY_CATEGORY` ON `gjgs`.`team_category` (`category_id` ASC) VISIBLE;

CREATE INDEX `FK_TEAM_CATEGORY_TEAM` ON `gjgs`.`team_category` (`team_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- 액티비티
INSERT INTO category (category_id, main_category, sub_category)
VALUES (1, '액티비티', null);
INSERT INTO category (category_id, main_category, sub_category)
VALUES (2, '액티비티', '보드');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (3, '액티비티', '클라이밍');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (4, '액티비티', '다이빙');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (5, '액티비티', '스키/스노우보드');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (6, '액티비티', '테니스');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (7, '액티비티', '배드민턴');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (8, '액티비티', '펜싱');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (9, '액티비티', '탁구');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (10, '액티비티', '사격');

-- 쿠킹
INSERT INTO category (category_id, main_category, sub_category)
VALUES (11, '쿠킹', null);
INSERT INTO category (category_id, main_category, sub_category)
VALUES (12, '쿠킹', '한식');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (13, '쿠킹', '양식');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (14, '쿠킹', '중식');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (15, '쿠킹', '일식');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (16, '쿠킹', '베이킹/디저트');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (17, '쿠킹', '떡/한과');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (18, '쿠킹', '바리스타');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (19, '쿠킹', '비건');

-- 뷰티/헬스
INSERT INTO category (category_id, main_category, sub_category)
VALUES (20, '뷰티/헬스', null);
INSERT INTO category (category_id, main_category, sub_category)
VALUES (21, '뷰티/헬스', '요가');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (22, '뷰티/헬스', '필라테스');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (23, '뷰티/헬스', '헬스');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (24, '뷰티/헬스', '얼굴');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (25, '뷰티/헬스', '헤어');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (26, '뷰티/헬스', '애견미용');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (27, '뷰티/헬스', '네일');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (28, '뷰티/헬스', '퍼스널컬러');

-- 댄스
INSERT INTO category (category_id, main_category, sub_category)
VALUES (29, '댄스', null);
INSERT INTO category (category_id, main_category, sub_category)
VALUES (30, '댄스', '방송댄스');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (31, '댄스', '재즈댄스');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (32, '댄스', '발레');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (33, '댄스', '한국무용');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (34, '댄스', '벨리댄스');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (35, '댄스', '비보이/스트릿댄스');

-- 미술
INSERT INTO category (category_id, main_category, sub_category)
VALUES (36, '미술', null);
INSERT INTO category (category_id, main_category, sub_category)
VALUES (37, '미술', '인물화');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (38, '미술', '서양화');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (39, '미술', '수제화');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (40, '미술', '파스텔');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (41, '미술', '드로잉');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (42, '미술', '만화/캐리커처');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (43, '미술', '캘리그라피');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (44, '미술', '사진');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (45, '미술', '영상편집');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (46, '미술', '페인팅');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (47, '미술', '타투');

-- 수공예
INSERT INTO category (category_id, main_category, sub_category)
VALUES (48, '수공예', null);
INSERT INTO category (category_id, main_category, sub_category)
VALUES (49, '수공예', '천연비누');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (50, '수공예', '입욕제');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (51, '수공예', '화장품');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (52, '수공예', '악세사리');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (53, '수공예', '향수');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (54, '수공예', '디퓨저');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (55, '수공예', '캔들');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (56, '수공예', '도예');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (57, '수공예', '미싱/재봉틀');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (58, '수공예', '자수');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (59, '수공예', '가죽');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (60, '수공예', '목공');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (61, '수공예', '페이퍼플라워');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (62, '수공예', '플라워');

-- 음악/예술
INSERT INTO category (category_id, main_category, sub_category)
VALUES (63, '음악/예술', null);
INSERT INTO category (category_id, main_category, sub_category)
VALUES (64, '음악/예술', '보컬');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (65, '음악/예술', '기타/베이스');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (66, '음악/예술', '드럼');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (67, '음악/예술', '피아노');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (68, '음악/예술', '작사/작곡');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (69, '음악/예술', '연기');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (70, '음악/예술', '전통악기');
INSERT INTO category (category_id, main_category, sub_category)
VALUES (71, '음악/예술', '랩');

-- 서울
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (1, '서울', null);
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (2, '서울', '강남/역삼/선릉/삼성');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (3, '서울', '서초/교대/방배');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (4, '서울', '홍대/합정/상수');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (5, '서울', '신촌/이대/아현/연희');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (6, '서울', '광화문/종로');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (7, '서울', '압구정/신사/논현/청담');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (8, '서울', '낙성대/서울대입구/신림');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (9, '서울', '도곡/대치/개포/수서');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (10, '서울', '마곡/방화/목동/신정');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (11, '서울', '망원/연남/성산/상암');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (12, '서울', '을지로/신당/동대문');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (13, '서울', '사당/이수/노량진/대방');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (14, '서울', '건대/구의/군자');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (15, '서울', '선유도/당산/여의도');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (16, '서울', '성수/왕십리/서울숲');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (17, '서울', '수유/미아/방학');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (18, '서울', '명동/회현/충무로');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (19, '서울', '영등포/문래/신길/대림');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (20, '서울', '이태원/용산/후암');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (21, '서울', '제기/청량/회기');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (22, '서울', '천호/길동');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (23, '서울', '공덕/마포/대흥');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (24, '서울', '성북/길음/안암');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (25, '서울', '잠실/송파/방이');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (26, '서울', '불광/연신내');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (27, '서울', '공릉/상계/면목/상봉');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (28, '서울', '대학로/동묘');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (29, '서울', '구로/신도림/가산/독산');

-- 경기
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (30, '경기', null);
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (31, '경기', '가평/남양주/구리');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (32, '경기', '고양');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (33, '경기', '과천/안양/의왕/군포');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (34, '경기', '김포');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (35, '경기', '성남');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (36, '경기', '수원');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (37, '경기', '시흥/광명/부천');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (38, '경기', '안산');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (39, '경기', '의정부/양주/동두천/포천');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (40, '경기', '여주/이천');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (41, '경기', '오산/평택/안성/화성');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (42, '경기', '용인');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (43, '경기', '파주');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (44, '경기', '하남/광주/양평');

-- 인천
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (45, '인천', null);
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (46, '인천', '계양/서구');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (47, '인천', '미추홀구/남동구/연수구');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (48, '인천', '강화/옹진');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (49, '인천', '동구/중구');
INSERT INTO zone (zone_id, main_zone, sub_zone)
VALUES (50, '인천', '부평');
